# Generated by Django 2.2.7 on 2019-11-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Empresas', '0001_initial'),
        ('Departamentos', '0001_initial'),
        ('Funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='Departamentos',
            field=models.ManyToManyField(to='Departamentos.Departamentos'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Empresas.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
