# Generated by Django 2.2.7 on 2019-11-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0002_auto_20191110_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
