# Generated by Django 2.2.7 on 2019-11-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0001_initial'),
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='Funcionarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Funcionarios.Funcionarios'),
        ),
    ]
